name: Assign Items to GitHub Project v2 (Project 4)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to GitHub Project
        uses: srggrs/assign-one-project-github-action@1.3.1
        env:
          MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          project: https://github.com/users/budrobundy69/projects/4
          column_name: To do
